<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VarianterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $varianter=array(
            array(
                'id'=>1,
                'produkt_id'=>1,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>27.5
            ),
            array(
                'id'=>2,
                'produkt_id'=>1,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>55
            ),
            array(
                'id'=>3,
                'produkt_id'=>1,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>137.5
            ),
            array(
                'id'=>4,
                'produkt_id'=>1,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>275
            ),
            array(
                'id'=>5,
                'produkt_id'=>1,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>550
            ),
            array(
                'id'=>6,
                'produkt_id'=>2,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>7,
                'produkt_id'=>2,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>8,
                'produkt_id'=>2,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>9,
                'produkt_id'=>2,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>10,
                'produkt_id'=>2,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>11,
                'produkt_id'=>3,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>12,
                'produkt_id'=>3,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>13,
                'produkt_id'=>3,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>112.5
            ),
            array(
                'id'=>14,
                'produkt_id'=>3,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>15,
                'produkt_id'=>3,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>16,
                'produkt_id'=>4,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>25
            ),
            array(
                'id'=>17,
                'produkt_id'=>4,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>50
            ),
            array(
                'id'=>18,
                'produkt_id'=>4,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>125
            ),
            array(
                'id'=>19,
                'produkt_id'=>4,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>250
            ),
            array(
                'id'=>20,
                'produkt_id'=>4,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>500
            ),
            array(
                'id'=>21,
                'produkt_id'=>5,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>32.5
            ),
            array(
                'id'=>22,
                'produkt_id'=>5,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>65
            ),
            array(
                'id'=>23,
                'produkt_id'=>5,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>162.5
            ),
            array(
                'id'=>24,
                'produkt_id'=>5,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>325
            ),
            array(
                'id'=>25,
                'produkt_id'=>5,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>650
            ),
            array(
                'id'=>26,
                'produkt_id'=>6,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>27,
                'produkt_id'=>6,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>28,
                'produkt_id'=>6,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>29,
                'produkt_id'=>6,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>30,
                'produkt_id'=>6,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>31,
                'produkt_id'=>7,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>29.5
            ),
            array(
                'id'=>32,
                'produkt_id'=>7,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>59
            ),
            array(
                'id'=>33,
                'produkt_id'=>7,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>147.5
            ),
            array(
                'id'=>34,
                'produkt_id'=>7,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>295
            ),
            array(
                'id'=>35,
                'produkt_id'=>7,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>590
            ),
            array(
                'id'=>36,
                'produkt_id'=>8,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>37,
                'produkt_id'=>8,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>38,
                'produkt_id'=>8,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>39,
                'produkt_id'=>8,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>40,
                'produkt_id'=>8,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>41,
                'produkt_id'=>9,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>37.5
            ),
            array(
                'id'=>42,
                'produkt_id'=>9,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>75
            ),
            array(
                'id'=>43,
                'produkt_id'=>9,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>187.5
            ),
            array(
                'id'=>44,
                'produkt_id'=>9,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>375
            ),
            array(
                'id'=>45,
                'produkt_id'=>9,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>750
            ),
            array(
                'id'=>46,
                'produkt_id'=>10,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>47,
                'produkt_id'=>10,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>48,
                'produkt_id'=>10,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>49,
                'produkt_id'=>10,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>50,
                'produkt_id'=>10,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>51,
                'produkt_id'=>11,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>27.5
            ),
            array(
                'id'=>52,
                'produkt_id'=>11,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>55
            ),
            array(
                'id'=>53,
                'produkt_id'=>11,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>137.5
            ),
            array(
                'id'=>54,
                'produkt_id'=>11,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>275
            ),
            array(
                'id'=>55,
                'produkt_id'=>11,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>550
            ),
            array(
                'id'=>56,
                'produkt_id'=>12,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>30
            ),
            array(
                'id'=>57,
                'produkt_id'=>12,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>60
            ),
            array(
                'id'=>58,
                'produkt_id'=>12,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>150
            ),
            array(
                'id'=>59,
                'produkt_id'=>12,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>300
            ),
            array(
                'id'=>60,
                'produkt_id'=>12,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>600
            ),
            array(
                'id'=>61,
                'produkt_id'=>13,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>62,
                'produkt_id'=>13,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>63,
                'produkt_id'=>13,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>64,
                'produkt_id'=>13,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>65,
                'produkt_id'=>13,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>66,
                'produkt_id'=>14,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>62.5
            ),
            array(
                'id'=>67,
                'produkt_id'=>14,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>125
            ),
            array(
                'id'=>68,
                'produkt_id'=>14,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>312.5
            ),
            array(
                'id'=>69,
                'produkt_id'=>14,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>625
            ),
            array(
                'id'=>70,
                'produkt_id'=>14,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>1250
            ),
            array(
                'id'=>71,
                'produkt_id'=>15,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>72,
                'produkt_id'=>15,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>73,
                'produkt_id'=>15,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>74,
                'produkt_id'=>15,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>75,
                'produkt_id'=>15,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>76,
                'produkt_id'=>16,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>77,
                'produkt_id'=>16,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>78,
                'produkt_id'=>16,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>79,
                'produkt_id'=>16,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>80,
                'produkt_id'=>16,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
            array(
                'id'=>81,
                'produkt_id'=>17,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>22.5
            ),
            array(
                'id'=>82,
                'produkt_id'=>17,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>45
            ),
            array(
                'id'=>83,
                'produkt_id'=>17,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>112.5
            ),
            array(
                'id'=>84,
                'produkt_id'=>17,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>225
            ),
            array(
                'id'=>85,
                'produkt_id'=>17,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>450
            ),
            array(
                'id'=>86,
                'produkt_id'=>18,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>25
            ),
            array(
                'id'=>87,
                'produkt_id'=>18,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>50
            ),
            array(
                'id'=>88,
                'produkt_id'=>18,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>125
            ),
            array(
                'id'=>89,
                'produkt_id'=>18,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>250
            ),
            array(
                'id'=>90,
                'produkt_id'=>18,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>500
            ),
            array(
                'id'=>91,
                'produkt_id'=>19,
                'titel'=>'50g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>24.5
            ),
            array(
                'id'=>92,
                'produkt_id'=>19,
                'titel'=>'100g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>49
            ),
            array(
                'id'=>93,
                'produkt_id'=>19,
                'titel'=>'250g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>122.5
            ),
            array(
                'id'=>94,
                'produkt_id'=>19,
                'titel'=>'500g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>245
            ),
            array(
                'id'=>95,
                'produkt_id'=>19,
                'titel'=>'1000g',
                'lager'=>100,
                'type'=>'vægt',
                'pris'=>490
            ),
        );

        DB::table('varianter')->insert($varianter);
    }
}
